[tool.black]
# Настройки инструмента black для форматирования кода
target-version = ["py36", "py37", "py38", "py310"]  # Целевые версии Python для форматирования
line-length = 79  # Максимальная длина строки кода
include = '\.pyi?$'  # Включить форматирование для файлов с расширениями .py и .pyi
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''  # Исключить файлы и директории из форматирования

[tool.flake8]
# Настройки инструмента flake8 для проверки стиля кодирования
max-line-length = 79  # Максимальная длина строки кода
ignore = []  # Список игнорируемых ошибок
exclude = [
    ".git",
    "__pycache__",
    "venv",
]  # Исключить файлы и директории из проверки стиля

[tool.isort]
# Настройки инструмента isort для сортировки импортов
profile = "black"  # Профиль настроек, основанный на black
multi_line_output = 3  # Форматирование многострочных импортов
include_trailing_comma = true  # Добавлять запятую после последнего элемента списка импортов
force_grid_wrap = 0  # Ограничение на количество импортов в одной строке
use_parentheses = true  # Использовать скобки при импорте из одного модуля
line_length = 79  # Максимальная длина строки кода
skip = ".venv,venv,env"  # Пропустить указанные директории при сортировке импортов
src_paths = ["src"]  # Пути к исходным файлам проекта

[tool.mypy]
# Настройки инструмента mypy для статической типизации
python_version = "3.10"  # Версия Python
plugins = []  # Плагины для mypy
mypy_path = "src"  # Путь к директории с исходными файлами
exclude = []  # Исключить файлы и директории из анализа типов
follow_imports = "silent"  # Обработка ошибок при импорте
warn_redundant_casts = true  # Предупреждать о лишних приведениях типов
warn_unused_ignores = false  # Не предупреждать о неиспользованных аннотациях типов
show_error_codes = true  # Выводить коды ошибок
namespace_packages = true  # Разрешить использование пространств имен пакетов

[[tool.mypy.overrides]]
# Переопределения настроек mypy для конкретных модулей
module = ["twilio.rest"]  # Модули, для которых применяются переопределения
ignore_missing_imports = true  # Игнорировать отсутствующие импорты

[tool.django-stubs]
# Настройки инструмента django-stubs для поддержки типизации Django
django_settings_module = "config.settings"  # Модуль настроек Django
